### ISSUE TITLE
Support for fallback handlers when event-specific class doesn't exist

### ISSUE THREAD

**Issue by ChrisHardie** [hotmeteor/receiver#10]
Thanks for this great package. I notice that right now, for any given driver if a webhook is sent with an event/topic that doesn't map to a handler class in that driver's namespace, the code just quietly finishes and returns success. 

I wonder if it would be helpful to allow the definition of a fallback class that would be used when no event-specific class is available? 

I could imagine implementing this by hardcoding a class name that would be used (e.g. "NoEventHandler.php") or by allowing users of the package to define a fallback class in the receiver definition, e.g. through `getFallbackClass(): string` or similar.

**Comment by hotmeteor** [comment]
This is a good idea! Let me see what I can whip up today.

**Comment by hotmeteor** [comment]
@ChrisHardie Let me know what you think about this implementation, you can see an example from the new docs:

https://github.com/hotmeteor/receiver/pull/11/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R148

**Comment by ChrisHardie** [comment]
@hotmeteor looks great to me! That was fast. 😀
