### ISSUE TITLE
Best way to validate $driver string in a request?

### ISSUE THREAD

**Issue by ChrisHardie** [hotmeteor/receiver#25]
Short version: is there a recommended method or function for determining if a `$driver` string specified in a request is valid?

Longer version: I have a service sending webhooks that wants to get a 200 OK back from a GET request to the webhook endpoint before it will activate the webhook. It doesn't use the "challenge" approach so I don't think the handshake method is going to work here. I'm adding a simple method in the controller that will be reached by a GET route, but I'd like to return 404 when the driver specified isn't valid, as a basic check against typos or an invalid driver being otherwise specified.

It looks like right now this package just relies on the illuminate/support package to throw an exception when the driver doesn't exist, but maybe there's a way to check that more intentionally? Something like `Receiver::driverExists($driver);`?

Thanks for any suggestions you can offer.

**Comment by hotmeteor** [comment]
Hey sorry.

I think I've just relied on route parameter validation in the past: https://laravel.com/docs/10.x/routing#parameters-regular-expression-constraints
