### ISSUE TITLE
IDE: Undefined method 'receive'

### ISSUE THREAD

**Issue by hmaesta** [hotmeteor/receiver#3]
**VS Code** with [PHP Intelephense](https://marketplace.visualstudio.com/items?itemName=bmewburn.vscode-intelephense-client) is complaining about `receive` function (or any other function after the first one).

<img width="633" alt="Screen Shot 2022-09-06 at 10 44 17" src="https://user-images.githubusercontent.com/741969/188651192-79affe95-450d-48d0-9397-067819e68476.png">

Code runs fine. Just IDE is complaining.

**Comment by hotmeteor** [comment]
@hmaesta Should be a little nicer now

**Comment by hmaesta** [comment]
Thanks, Adam!
