### ISSUE TITLE
Unclear documentation

### ISSUE THREAD

**Issue by goodevilgenius** [hotmeteor/receiver#9]
In you README, it states:

> Simply implement the `verify` method in your provider and return true or false if it passes.

Likewise, it states:

> To facilitate this, implement the `handshake` method in your provider

However, both of the examples for these two methods show them being on the controller, rather than the provider.

If both of these methods are on the controller, it doesn't make it possible to group the verification and handshake with the provider itself. In any case, the documentation is confusing.

**Comment by hotmeteor** [comment]
Feel free to create a PR that improves it if I don't get to it first!
